//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Otel
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Допуск.
    /// </summary>
    // *** Start programmer edit section *** (Допуск CustomAttributes)

    // *** End programmer edit section *** (Допуск CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДопускE", new string[] {
            "Комнаты as \'Комнаты\'",
            "Комнаты.КомнатаОт as \'КомнатыОт\'",
            "Гости as \'Гости\'",
            "Гости.Комната as \'КомнатаГостя\'",
            "Комнаты.Отели.Наименования as \'Наименование\'",
            "Комнаты.Отели as \'Отели\'",
            "Гости.Авторизация.Имя as \'Имя\'",
            "Гости.Авторизация.Фамилия as \'Фамилия\'",
            "Гости.Авторизация as \'Авторизация\'",
            "Доступ as \'Доступ\'"}, Hidden=new string[] {
            "Комнаты.КомнатаОт",
            "Гости.Комната",
            "Комнаты.Отели.Наименования",
            "Гости.Авторизация.Имя",
            "Гости.Авторизация.Фамилия"})]
    [MasterViewDefineAttribute("ДопускE", "Комнаты", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ID")]
    [View("ДопускL", new string[] {
            "Гости.Авторизация.Имя as \'Имя\'",
            "Гости.Авторизация.Фамилия as \'Фамилия\'",
            "Комнаты.Отели.Наименования as \'Наименование\'",
            "Комнаты.КомнатаОт as \'КомнатаОт\'",
            "Гости.Комната as \'КомнатаГостя\'",
            "Доступ as \'Доступ\'"})]
    public class Допуск : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Otel.Доступа fДоступ;
        
        private IIS.Otel.Гости fГости;
        
        private IIS.Otel.Комнаты fКомнаты;
        
        // *** Start programmer edit section *** (Допуск CustomMembers)

        // *** End programmer edit section *** (Допуск CustomMembers)

        
        /// <summary>
        /// Доступ.
        /// </summary>
        // *** Start programmer edit section *** (Допуск.Доступ CustomAttributes)

        // *** End programmer edit section *** (Допуск.Доступ CustomAttributes)
        public virtual IIS.Otel.Доступа Доступ
        {
            get
            {
                // *** Start programmer edit section *** (Допуск.Доступ Get start)

                // *** End programmer edit section *** (Допуск.Доступ Get start)
                IIS.Otel.Доступа result = this.fДоступ;
                // *** Start programmer edit section *** (Допуск.Доступ Get end)

                // *** End programmer edit section *** (Допуск.Доступ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Допуск.Доступ Set start)

                // *** End programmer edit section *** (Допуск.Доступ Set start)
                this.fДоступ = value;
                // *** Start programmer edit section *** (Допуск.Доступ Set end)

                // *** End programmer edit section *** (Допуск.Доступ Set end)
            }
        }
        
        /// <summary>
        /// Допуск.
        /// </summary>
        // *** Start programmer edit section *** (Допуск.Гости CustomAttributes)

        // *** End programmer edit section *** (Допуск.Гости CustomAttributes)
        [PropertyStorage(new string[] {
                "Гости"})]
        [NotNull()]
        public virtual IIS.Otel.Гости Гости
        {
            get
            {
                // *** Start programmer edit section *** (Допуск.Гости Get start)

                // *** End programmer edit section *** (Допуск.Гости Get start)
                IIS.Otel.Гости result = this.fГости;
                // *** Start programmer edit section *** (Допуск.Гости Get end)

                // *** End programmer edit section *** (Допуск.Гости Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Допуск.Гости Set start)

                // *** End programmer edit section *** (Допуск.Гости Set start)
                this.fГости = value;
                // *** Start programmer edit section *** (Допуск.Гости Set end)

                // *** End programmer edit section *** (Допуск.Гости Set end)
            }
        }
        
        /// <summary>
        /// Допуск.
        /// </summary>
        // *** Start programmer edit section *** (Допуск.Комнаты CustomAttributes)

        // *** End programmer edit section *** (Допуск.Комнаты CustomAttributes)
        [PropertyStorage(new string[] {
                "Комнаты"})]
        [NotNull()]
        public virtual IIS.Otel.Комнаты Комнаты
        {
            get
            {
                // *** Start programmer edit section *** (Допуск.Комнаты Get start)

                // *** End programmer edit section *** (Допуск.Комнаты Get start)
                IIS.Otel.Комнаты result = this.fКомнаты;
                // *** Start programmer edit section *** (Допуск.Комнаты Get end)

                // *** End programmer edit section *** (Допуск.Комнаты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Допуск.Комнаты Set start)

                // *** End programmer edit section *** (Допуск.Комнаты Set start)
                this.fКомнаты = value;
                // *** Start programmer edit section *** (Допуск.Комнаты Set end)

                // *** End programmer edit section *** (Допуск.Комнаты Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДопускE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДопускE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДопускE", typeof(IIS.Otel.Допуск));
                }
            }
            
            /// <summary>
            /// "ДопускL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДопускL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДопускL", typeof(IIS.Otel.Допуск));
                }
            }
        }
    }
}
