//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Otel
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Звезда.
    /// </summary>
    // *** Start programmer edit section *** (Звезда CustomAttributes)

    // *** End programmer edit section *** (Звезда CustomAttributes)
    public enum Звезда
    {
        
        // *** Start programmer edit section *** (Звезда.1_Звезда CustomAttributes)

        // *** End programmer edit section *** (Звезда.1_Звезда CustomAttributes)
        1_Звезда,
        
        // *** Start programmer edit section *** (Звезда.2_Звезда CustomAttributes)

        // *** End programmer edit section *** (Звезда.2_Звезда CustomAttributes)
        2_Звезда,
        
        // *** Start programmer edit section *** (Звезда.3_Звезда CustomAttributes)

        // *** End programmer edit section *** (Звезда.3_Звезда CustomAttributes)
        3_Звезда,
        
        // *** Start programmer edit section *** (Звезда.4_Звезда CustomAttributes)

        // *** End programmer edit section *** (Звезда.4_Звезда CustomAttributes)
        4_Звезда,
        
        // *** Start programmer edit section *** (Звезда.5_Звезда CustomAttributes)

        // *** End programmer edit section *** (Звезда.5_Звезда CustomAttributes)
        5_Звезда,
    }
}
