//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Otel
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Комнаты.
    /// </summary>
    // *** Start programmer edit section *** (Комнаты CustomAttributes)

    // *** End programmer edit section *** (Комнаты CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КомнатыE", new string[] {
            "ID as \'ID\'",
            "КомнатаОт as \'Комната от\'",
            "Этаж as \'Этаж\'",
            "Отели as \'Отели\'",
            "Отели.Наименования as \'Наименования\'"}, Hidden=new string[] {
            "Отели.Наименования"})]
    [MasterViewDefineAttribute("КомнатыE", "Отели", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименования")]
    [View("КомнатыL", new string[] {
            "ID as \'ID\'",
            "КомнатаОт as \'Комната от\'",
            "Этаж as \'Этаж\'",
            "Отели.Наименования as \'Наименования\'"})]
    public class Комнаты : ICSSoft.STORMNET.DataObject
    {
        
        private int fID;
        
        private int fКомнатаОт;
        
        private int fЭтаж;
        
        private IIS.Otel.Отели fОтели;
        
        // *** Start programmer edit section *** (Комнаты CustomMembers)

        // *** End programmer edit section *** (Комнаты CustomMembers)

        
        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (Комнаты.ID CustomAttributes)

        // *** End programmer edit section *** (Комнаты.ID CustomAttributes)
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (Комнаты.ID Get start)

                // *** End programmer edit section *** (Комнаты.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (Комнаты.ID Get end)

                // *** End programmer edit section *** (Комнаты.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Комнаты.ID Set start)

                // *** End programmer edit section *** (Комнаты.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (Комнаты.ID Set end)

                // *** End programmer edit section *** (Комнаты.ID Set end)
            }
        }
        
        /// <summary>
        /// КомнатаОт.
        /// </summary>
        // *** Start programmer edit section *** (Комнаты.КомнатаОт CustomAttributes)

        // *** End programmer edit section *** (Комнаты.КомнатаОт CustomAttributes)
        public virtual int КомнатаОт
        {
            get
            {
                // *** Start programmer edit section *** (Комнаты.КомнатаОт Get start)

                // *** End programmer edit section *** (Комнаты.КомнатаОт Get start)
                int result = this.fКомнатаОт;
                // *** Start programmer edit section *** (Комнаты.КомнатаОт Get end)

                // *** End programmer edit section *** (Комнаты.КомнатаОт Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Комнаты.КомнатаОт Set start)

                // *** End programmer edit section *** (Комнаты.КомнатаОт Set start)
                this.fКомнатаОт = value;
                // *** Start programmer edit section *** (Комнаты.КомнатаОт Set end)

                // *** End programmer edit section *** (Комнаты.КомнатаОт Set end)
            }
        }
        
        /// <summary>
        /// Этаж.
        /// </summary>
        // *** Start programmer edit section *** (Комнаты.Этаж CustomAttributes)

        // *** End programmer edit section *** (Комнаты.Этаж CustomAttributes)
        public virtual int Этаж
        {
            get
            {
                // *** Start programmer edit section *** (Комнаты.Этаж Get start)

                // *** End programmer edit section *** (Комнаты.Этаж Get start)
                int result = this.fЭтаж;
                // *** Start programmer edit section *** (Комнаты.Этаж Get end)

                // *** End programmer edit section *** (Комнаты.Этаж Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Комнаты.Этаж Set start)

                // *** End programmer edit section *** (Комнаты.Этаж Set start)
                this.fЭтаж = value;
                // *** Start programmer edit section *** (Комнаты.Этаж Set end)

                // *** End programmer edit section *** (Комнаты.Этаж Set end)
            }
        }
        
        /// <summary>
        /// Комнаты.
        /// </summary>
        // *** Start programmer edit section *** (Комнаты.Отели CustomAttributes)

        // *** End programmer edit section *** (Комнаты.Отели CustomAttributes)
        [PropertyStorage(new string[] {
                "Отели"})]
        [NotNull()]
        public virtual IIS.Otel.Отели Отели
        {
            get
            {
                // *** Start programmer edit section *** (Комнаты.Отели Get start)

                // *** End programmer edit section *** (Комнаты.Отели Get start)
                IIS.Otel.Отели result = this.fОтели;
                // *** Start programmer edit section *** (Комнаты.Отели Get end)

                // *** End programmer edit section *** (Комнаты.Отели Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Комнаты.Отели Set start)

                // *** End programmer edit section *** (Комнаты.Отели Set start)
                this.fОтели = value;
                // *** Start programmer edit section *** (Комнаты.Отели Set end)

                // *** End programmer edit section *** (Комнаты.Отели Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КомнатыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КомнатыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КомнатыE", typeof(IIS.Otel.Комнаты));
                }
            }
            
            /// <summary>
            /// "КомнатыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КомнатыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КомнатыL", typeof(IIS.Otel.Комнаты));
                }
            }
        }
    }
}
